### ISSUE TITLE
UE 5.4 Version

### ISSUE THREAD

**Issue by elai950** [KieranNewland/RepGraph#1]
Will you do an updated version for UE 5.4 ?
Currently lot of code in this library is already deprecated, it is very confusing to refactor it without really really understand what you doing.

Either way, thank you very much for this information about replication graph! not very much out there yet.

**Comment by KieranNewland** [comment]
Hi. Thanks for the warning. There was just the one deprecation issue that has now been resolved but it was unrelated to the Replication Graph itself. I've tested against Unreal 5.5.

I'm glad to hear the info is of use!
